package com.kubefn.runtime.introspection;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

/**
 * The Causal State Introspection capture engine — KubeFn's core
 * observability primitive.
 *
 * <p>This engine sits on the hot path of every request and captures
 * structured causal events into a lock-free ring buffer. Events are
 * generated by the {@code RequestDispatcher}, {@code HeapExchangeImpl},
 * {@code FunctionCircuitBreaker}, and {@code DrainManager} at key
 * lifecycle points.
 *
 * <p>The engine provides two interfaces:
 * <ul>
 *   <li><strong>Capture API</strong> — called from the hot path with
 *       minimal overhead (lock-free append to pre-allocated ring)</li>
 *   <li><strong>Query API</strong> — called from the admin handler to
 *       build traces, search history, and feed the replay engine</li>
 * </ul>
 *
 * <p>Thread safety: all methods are safe for concurrent access from
 * multiple virtual threads. The capture methods are designed for
 * zero-contention on the fast path using atomic operations only.
 *
 * <p>Usage from RequestDispatcher:
 * <pre>{@code
 *   engine.captureRequestStart(requestId, group, function, revision);
 *   engine.captureFunctionStart(requestId, group, function, revision);
 *   // ... function executes ...
 *   engine.captureFunctionEnd(requestId, group, function, durationNanos, null);
 *   engine.captureRequestEnd(requestId, totalNanos, null);
 * }</pre>
 */
public class CausalCaptureEngine {

    private static final Logger log = LoggerFactory.getLogger(CausalCaptureEngine.class);

    private final CausalEventRing ring;
    private final RequestTraceAssembler assembler;
    private final AtomicLong eventIdGenerator = new AtomicLong(0);

    /** Whether capture is enabled. Can be toggled at runtime via admin API. */
    private volatile boolean enabled = true;

    /**
     * Creates an engine with the default ring buffer capacity.
     */
    public CausalCaptureEngine() {
        this(new CausalEventRing());
    }

    /**
     * Creates an engine with a custom ring buffer capacity.
     *
     * @param ringCapacity maximum events to retain
     */
    public CausalCaptureEngine(int ringCapacity) {
        this(new CausalEventRing(ringCapacity));
    }

    /**
     * Creates an engine with an externally configured ring buffer.
     *
     * @param ring the ring buffer to use for event storage
     */
    public CausalCaptureEngine(CausalEventRing ring) {
        this.ring = ring;
        this.assembler = new RequestTraceAssembler();
        log.info("CausalCaptureEngine initialized with ring capacity: {}", ring.capacity());
    }

    // ───────────────────────────────────────────────────────────────────
    //  Capture API — called from hot path
    // ───────────────────────────────────────────────────────────────────

    /**
     * Captures the start of a new request entering the runtime.
     */
    public void captureRequestStart(String requestId, String group, String function, String revision) {
        emit(requestId, EventType.REQUEST_START, group, function, revision,
                null, null, 0, 0, null);
    }

    /**
     * Captures the completion of a request.
     *
     * @param error null if the request completed successfully
     */
    public void captureRequestEnd(String requestId, long durationNanos, String error) {
        emit(requestId, EventType.REQUEST_END, null, null, null,
                null, null, 0, durationNanos, error);
    }

    /**
     * Captures the start of a function invocation within a request.
     */
    public void captureFunctionStart(String requestId, String group, String function, String revision) {
        emit(requestId, EventType.FUNCTION_START, group, function, revision,
                null, null, 0, 0, null);
    }

    /**
     * Captures the completion of a function invocation.
     *
     * @param error null if the function completed successfully
     */
    public void captureFunctionEnd(String requestId, String group, String function,
                                   long durationNanos, String error) {
        emit(requestId, EventType.FUNCTION_END, group, function, null,
                null, null, 0, durationNanos, error);
    }

    /**
     * Captures a heap publish (write) operation.
     */
    public void captureHeapPublish(String requestId, String key, String type, long version) {
        emit(requestId, EventType.HEAP_PUBLISH, null, null, null,
                key, type, version, 0, null);
    }

    /**
     * Captures a heap get operation (hit or miss).
     *
     * @param hit true if the key was found in the heap
     */
    public void captureHeapGet(String requestId, String key, String type, boolean hit) {
        EventType eventType = hit ? EventType.HEAP_GET_HIT : EventType.HEAP_GET_MISS;
        emit(requestId, eventType, null, null, null,
                key, type, 0, 0, null);
    }

    /**
     * Captures a heap remove operation.
     */
    public void captureHeapRemove(String requestId, String key) {
        emit(requestId, EventType.HEAP_REMOVE, null, null, null,
                key, null, 0, 0, null);
    }

    /**
     * Captures a circuit breaker trip for a function.
     */
    public void captureCircuitBreakerTrip(String requestId, String group, String function) {
        emit(requestId, EventType.CIRCUIT_BREAKER_TRIP, group, function, null,
                null, null, 0, 0, "Circuit breaker tripped");
    }

    /**
     * Captures an error event.
     */
    public void captureError(String requestId, String group, String function, String errorMessage) {
        emit(requestId, EventType.ERROR, group, function, null,
                null, null, 0, 0, errorMessage);
    }

    /**
     * Captures a pipeline start event.
     */
    public void capturePipelineStart(String requestId, String group, String pipelineName) {
        emit(requestId, EventType.PIPELINE_START, group, pipelineName, null,
                null, null, 0, 0, null);
    }

    /**
     * Captures a pipeline end event.
     */
    public void capturePipelineEnd(String requestId, String group, String pipelineName,
                                   long durationNanos) {
        emit(requestId, EventType.PIPELINE_END, group, pipelineName, null,
                null, null, 0, durationNanos, null);
    }

    /**
     * Captures a drain lifecycle event.
     */
    public void captureDrainStart(String requestId, String group) {
        emit(requestId, EventType.DRAIN_START, group, null, null,
                null, null, 0, 0, null);
    }

    /**
     * Captures a drain completion event.
     */
    public void captureDrainEnd(String requestId, String group, long durationNanos) {
        emit(requestId, EventType.DRAIN_END, group, null, null,
                null, null, 0, durationNanos, null);
    }

    // ───────────────────────────────────────────────────────────────────
    //  Query API — called from admin handler / replay engine
    // ───────────────────────────────────────────────────────────────────

    /**
     * Builds a complete trace for the given request.
     *
     * @param requestId the request to trace
     * @return the assembled trace, or null if no events found
     */
    public RequestTrace getTrace(String requestId) {
        if (requestId == null) {
            return null;
        }
        List<CausalEvent> events = ring.getByRequestId(requestId, Integer.MAX_VALUE);
        if (events.isEmpty()) {
            return null;
        }
        return assembler.assemble(requestId, events);
    }

    /**
     * Returns traces for the most recent requests.
     *
     * @param limit maximum number of traces to return
     * @return list of traces, most recent first
     */
    public List<RequestTrace> recentTraces(int limit) {
        if (limit <= 0) {
            return List.of();
        }
        List<String> requestIds = ring.recentRequestIds(limit);
        List<RequestTrace> traces = new ArrayList<>(requestIds.size());
        for (String id : requestIds) {
            RequestTrace trace = getTrace(id);
            if (trace != null) {
                traces.add(trace);
            }
        }
        return traces;
    }

    /**
     * Searches traces with optional filters. All filter parameters are
     * nullable — null means "don't filter on this dimension".
     *
     * @param group         filter by function group name (null = any)
     * @param function      filter by function name (null = any)
     * @param minDurationMs minimum total duration in milliseconds (null = any)
     * @param hasErrors     if non-null, filter to traces with/without errors
     * @param limit         maximum number of results
     * @return matching traces, most recent first
     */
    public List<RequestTrace> searchTraces(String group, String function,
                                           Double minDurationMs, Boolean hasErrors,
                                           int limit) {
        if (limit <= 0) {
            return List.of();
        }

        // Get a broad set of recent request IDs to scan
        int scanLimit = Math.min(limit * 10, 1000);
        List<String> requestIds = ring.recentRequestIds(scanLimit);
        List<RequestTrace> results = new ArrayList<>();

        for (String id : requestIds) {
            if (results.size() >= limit) {
                break;
            }

            RequestTrace trace = getTrace(id);
            if (trace == null) {
                continue;
            }

            // Apply filters
            if (group != null && !group.equals(trace.entryGroup())) {
                continue;
            }
            if (function != null && !function.equals(trace.entryFunction())) {
                continue;
            }
            if (minDurationMs != null && trace.totalTimeMs() < minDurationMs) {
                continue;
            }
            if (hasErrors != null && trace.hasErrors() != hasErrors) {
                continue;
            }

            results.add(trace);
        }

        return results;
    }

    // ───────────────────────────────────────────────────────────────────
    //  Admin / lifecycle
    // ───────────────────────────────────────────────────────────────────

    /**
     * Returns the underlying ring buffer. Exposed for the admin handler
     * and replay engine.
     */
    public CausalEventRing ring() {
        return ring;
    }

    /**
     * Returns the trace assembler. Exposed for the replay engine.
     */
    public RequestTraceAssembler assembler() {
        return assembler;
    }

    /**
     * Enables or disables event capture. When disabled, all capture
     * methods become no-ops. Query methods still work on existing data.
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
        log.info("CausalCaptureEngine capture {}", enabled ? "enabled" : "disabled");
    }

    /**
     * Returns whether capture is currently enabled.
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Returns summary statistics about the engine state.
     */
    public EngineStats stats() {
        return new EngineStats(
                ring.size(),
                ring.capacity(),
                ring.totalEventsWritten(),
                eventIdGenerator.get(),
                enabled
        );
    }

    /**
     * Summary statistics for the capture engine.
     */
    public record EngineStats(
            int eventsRetained,
            int ringCapacity,
            long totalEventsWritten,
            long totalEventsGenerated,
            boolean captureEnabled
    ) {
        public double fillRatio() {
            return ringCapacity == 0 ? 0.0 : (double) eventsRetained / ringCapacity;
        }
    }

    // ───────────────────────────────────────────────────────────────────
    //  Internal
    // ───────────────────────────────────────────────────────────────────

    private void emit(String requestId, EventType type, String group, String function,
                      String revision, String heapKey, String heapObjectType,
                      long heapVersion, long durationNanos, String detail) {
        if (!enabled) {
            return;
        }

        long eventId = eventIdGenerator.getAndIncrement();
        long timestampNanos = System.nanoTime();

        CausalEvent event = new CausalEvent(
                eventId,
                timestampNanos,
                requestId,
                type,
                group,
                function,
                revision,
                heapKey,
                heapObjectType,
                heapVersion,
                durationNanos,
                detail
        );

        ring.append(event);
    }
}
