apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubefn.fullname" . }}-runtime
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubefn.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  type: ClusterIP
  selector:
    {{- include "kubefn.runtime.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: admin
      port: {{ .Values.runtime.adminPort }}
      targetPort: admin
      protocol: TCP
